name: Moonbase Beta - Puhlish Disk
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Zip SSD
        run: zip -ur Moonbase_Beta.zip *.ssd

      - uses: actions/upload-artifact@v2
        with:
          name: Moonbase_Beta_Zip
          path: Moonbase_Beta.zip
